# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  project: '**/*.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  IISDeploymentType: 'IISWebsite'
  ActionIISWebsite: 'CreateOrUpdateWebsite'
  WebsiteName: 'Default Web Site'
  AddBinding: 'True'
  Bindings: '{"bindings":[{"protocol":"http","ipAddress":"All Unassigned","port":"80","hostname":"","sslThumbprint":"","sniFlag":false}]}'
   
steps:

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: MSBuild@1
  inputs:
    solution: '$(project)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    msbuildArguments: '/p:OutputPath=$(Build.ArtifactStagingDirectory)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: PublishBuildArtifacts@1
  # inputs:
  #   ArtifactName: 'drop'
  #   pathToPublish: '$(build.artifactStagingDirectory)' 

- task: IISWebAppManagementOnMachineGroup@0
  inputs:
    IISDeploymentType: 'IISWebsite'
    ActionIISWebsite: 'CreateOrUpdateWebsite'
    WebsiteName: 'Default Web Site'
    WebsitePhysicalPath: 'C:\Projects\ITSS'
    WebsitePhysicalPathAuth: 'WebsiteUserPassThrough'
    AddBinding: true
    CreateOrUpdateAppPoolForWebsite: true
    AppPoolNameForWebsite: 'DefaultAppPool'
    DotNetVersionForWebsite: 'v4.0'
    PipeLineModeForWebsite: 'Integrated'
    AppPoolIdentityForWebsite: 'ApplicationPoolIdentity'
  
- task: IISWebAppDeploymentOnMachineGroup@0
  displayName: 'Deploy ITSS Website'
  inputs:
    WebSiteName: 'Default Web Site'
    VirtualApplication: 'ITSS'
    Package: '$(build.artifactStagingDirectory)\_PublishedWebsites\ITSS'
#  - task: IISWebAppDeploymentOnMachineGroup@0
#    displayName: 'Deploy IIS Website/App: '
#    inputs:
#     WebSiteName: '$(Parameters.WebsiteName)'
#     VirtualApplication: ITSS
#     Package: '$(build.artifactStagingDirectory)\_PublishedWebsites\ITSS'
