# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  project: '**/ITSS/ITSS.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  OUTPUT_DIRECTORY: '../Output/ITSS'
  ARTIFACTS_DIRECTORY: './Output/ITSS/_PublishedWebsites/ITSS/'


steps:
- script: |
    echo $(Build.ArtifactStagingDirectory)
    echo $(OUTPUT_DIRECTORY)

# - task: NuGetToolInstaller@1

# - task: NuGetCommand@2
#   inputs:
#     restoreSolution: '$(solution)'

# - task: VSBuild@1
#   inputs:
#     solution: '$(project)'
#     msbuildArgs: '/p:DeployOnBuild=true /p:OutputPath=$(OUTPUT_DIRECTORY) /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(ARTIFACTS_DIRECTORY)"'
#     platform: '$(buildPlatform)'
#     configuration: '$(buildConfiguration)'
