# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- none

variables:
  IISWebSiteName: 'Default Web Site'

resources:
  pipelines:
    - pipeline: 'buildPipeline'
      project: 'ITSS'
      source: 'buildPipeline'
      branch: 'master'

stages:
  - stage: DeployWebsite
    displayName: 'Deploy Website'
    pool:
      vmImage: 'windows-latest'
    jobs:
      - deployment: DeployWebsite
        displayName: 'Deploy Website'
        environment: 'Dev.CPC-spate-I0J1I'
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: none
                - download: 'buildPipeline'
                  name: 'DownloadBuildArtifacts'
                  displayName: 'Download Build Artifacts'
                  artifact: 'drop'
                
                - task: IISWebAppManagementOnMachineGroup@0
                  name: 'StopIIS'
                  displayName: 'Stop IIS Website'
                  inputs:
                    IISDeploymentType: 'IISWebsite'
                    ActionIISWebsite: 'StopWebsite'
                    StartStopWebsiteName: 'Default Web Site'
                - task: IISWebAppDeploymentOnMachineGroup@0
                  name: 'DeployIIS'
                  displayName: 'Deploy to IIS'
                  inputs:
                    WebSiteName: 'Default Web Site'
                    VirtualApplication: 'ITSS'
                    Package: '$(Pipeline.Workspace)\buildPipeline\drop\_PublishedWebsites\ITSS'
                
                - task: IISWebAppManagementOnMachineGroup@0
                  name: 'StartIIS'
                  displayName: 'Start IIS Website'
                  inputs:
                    IISDeploymentType: 'IISWebsite'
                    ActionIISWebsite: 'StartWebsite'
                    StartStopWebsiteName: 'Default Web Site'

